### ISSUE TITLE
RHEL-07-020260 - yum-cron setup fails on CentOS docker image

### ISSUE THREAD

**Issue by shepdelacreme** [MindPointGroup/RHEL7-STIG#177]
When running this role via the molecule tests, this task fails on the centos/systemd docker image.

Need to validate if this is just an issue with the CentOS image or across other images as well.

```yaml
      - block:
            - name: "MEDIUM | RHEL-07-020260 | PATCH | Vendor packaged system security patches and updates must be installed and up to date. | Install yum-cron"
              yum:
                  name: yum-cron
                  state: "{{ (rhel7stig_auto_package_updates.enabled) | ternary('present','absent')}}"
                  enablerepo: "{{ (ansible_distribution == 'RedHat') | ternary('rhel-7-' +
                          (rhel_07_020260_rhel_type.rc == 0) | ternary('workstation', 'server') +
                          '-optional-rpms','') }}"
        rescue:
              # Might be an AWS RHEL instance, try it...
            - name: "MEDIUM | RHEL-07-020260 | PATCH | Vendor packaged system security patches and updates must be installed and up to date. | Install yum-cron"
              yum:
                  name: yum-cron
                  state: "{{ (rhel7stig_auto_package_updates.enabled) | ternary('present','absent')}}"
                  enablerepo: rhui-REGION-rhel-server-optional
```

First failure
```
    TASK [RHEL7-STIG : MEDIUM | RHEL-07-020260 | PATCH | Vendor packaged system security patches and updates must be installed and up to date. | Install yum-cron] ***
    fatal: [centOS]: FAILED! => {"changed": false, "msg": "Error setting/accessing repos: Error getting repository data for , repository not found"}
```

It also has a rescue statement that is attempted that fails as well.
```
    TASK [RHEL7-STIG : MEDIUM | RHEL-07-020260 | PATCH | Vendor packaged system security patches and updates must be installed and up to date. | Install yum-cron] ***
    fatal: [centOS]: FAILED! => {"changed": false, "msg": "Error setting/accessing repos: Error getting repository data for rhui-REGION-rhel-server-optional, repository not found"}
```
