### ISSUE TITLE
RHEL-07-010010 failing oscap scan due to quoting problems in task

### ISSUE THREAD

**Issue by defionscode** [MindPointGroup/RHEL7-STIG#189]
The following task returns nothing to `stdout` and thus fails to trigger updates on the subsequent command.

```yaml
      - name: "HIGH | RHEL-07-010010 | AUDIT | The file permissions, ownership, and group membership of system files and commands must match the vendor values."
        shell: 'rpm -Va --nolinkto --nofiledigest --nosize --nomtime --nodigest --nosignature | grep -E ''^(.M|.....U|......G)'' | tee /dev/stderr | cut -c13- | sed ''s/^ //'' | xargs rpm -qf --qf=''%{name}\n'' | sort -u'
        args:
            warn: no
        check_mode: no
        failed_when: no
        changed_when: rhel_07_010010_audit.stdout != ""
        register: rhel_07_010010_audit
```

I have a fix ready, PR inbound
