### ISSUE TITLE
Adjusting find commands to traverse all local filesystems (RHEL-07-020320, RHEL-07-020330, etc.)

### ISSUE THREAD

**Issue by mikerenfro** [MindPointGroup/RHEL7-STIG#64]
Though the letter of 07-020320 and related rules with `find` commands specify particular filesystem types and mount points, I suspect they really intend for all local filesystems to be examined, regardless of filesystem type (xfs, ext4, etc.) and mount point (`/`, `/boot`, etc.).

Here's a proof of concept for 020320 and 020330 that will find files with missing UIDs and GIDs in `/`, `/boot`, etc. Will make a proper branch and PR if this looks worthwhile.

[localdisks.yml.txt](https://github.com/MindPointGroup/RHEL7-STIG/files/1816797/localdisks.yml.txt)

**Comment by mikerenfro** [comment]
Don't know why this didn't paste in correctly before.
```yaml
---

- hosts: localhost

  tasks:
    - name: "PRELIM | RHEL-07-020320 | All files and directories must have a valid owner."
      command: find "{{ item.mount }}" -xdev -nouser
      changed_when: false
      register: rhel_07_020320_audit
      when: item['device'].startswith('/dev')
      with_items:
        - "{{ ansible_mounts }}"

    - name: "MEDIUM | RHEL-07-020320 | PATCH | All files and directories must have a valid owner."
      debug:
        msg: |
          Manual intervention is required - files and directories were found in {{ item.item.mount }} are missing a user:
            {{ item.stdout_lines | join('\n') }}
      when:
        - item.stdout_lines is defined
        - item.stdout_lines | length > 0
      with_items: "{{ rhel_07_020320_audit.results }}"

    - name: "PRELIM | RHEL-07-020330 | All files and directories must have a valid group owner."
      command: find "{{ item.mount }}" -xdev -nogroup
      changed_when: false
      register: rhel_07_020330_audit
      when: item['device'].startswith('/dev')
      with_items:
        - "{{ ansible_mounts }}"

    - name: "MEDIUM | RHEL-07-020330 | PATCH | All files and directories must have a valid group owner."
      debug:
        msg: |
          Manual intervention is required - files and directories were found in {{ item.item.mount }} are missing a group:
            {{ item.stdout_lines | join('\n') }}
      when:
        - item.stdout_lines is defined
        - item.stdout_lines | length > 0
      with_items: "{{ rhel_07_020330_audit.results }}"
```
